name = "stratus"
version = "0.9.7"

description = "A Gleam WebSocket client"
licences = ["Apache-2.0"]
repository = { type = "github", user = "rawhat", repo = "stratus" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 1.0.0"
gleam_erlang = ">= 0.24.0 and < 1.0.0"
gleam_otp = ">= 0.9.0 and < 1.0.0"
gleam_http = ">= 3.5.0 and < 5.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"
logging = ">= 1.0.0 and < 2.0.0"
gramps = ">= 3.0.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
repeatedly = ">= 2.1.0 and < 3.0.0"
birl = ">= 1.5.0 and < 2.0.0"
